user:
  max_name: 140
  max_email: 140
  min_password: 6
session:
  remember: 1
rows: 50
avatar_size: 50
reset_password_timeout: 2
content_max: 140
picture_size: 5
picture_height: 400
picture_width: 400
picture_type: "image/jpeg,image/gif,image/png"
